### PR TITLE
Configure Dependabot

### PR DESCRIPTION
**Pull request by sjparkinson**
Adds vanilla Dependabot configuration for Composer.

### CODE REVIEW

**Comment by alexoanea** [comment]
@sjparkinson is there a way to manually trigger a run of this or do we have to wait 24h ? would like to see what it does before approving it

**Comment by sjparkinson** [comment]
No manual way until it's merged. Once merged there's options we can click to trigger a Dependabot run if it doesn't do one straight away.

Have a look at https://github.com/mention-me/MentionMe/pulls?q=is%3Aopen+is%3Apr+label%3Acomposer+label%3Adependencies to get an idea of what sort of pull requests are opened.

**Comment by sjparkinson** [comment]
Because this is a library, I think we'd need `composer.lock` in `.gitignore` too now that I think about it. So that we only get PRs for major versions etc. outside of the ranges in `composer.json`.

**Comment by sjparkinson** [comment]
OH! This package doesn't depend on any other packages at the moment! So Dependabot isn't going to do anything. Should it not depend on wherever the `Magento\Framework` namespace comes from?

**Comment by sjparkinson** [comment]
Going to close this for now rather than having us give it focus outside of a prospective day.

**Comment by alexoanea** [comment]
> OH! This package doesn't depend on any other packages at the moment! So Dependabot isn't going to do anything. Should it not depend on wherever the `Magento\Framework` namespace comes from?

The way the extension works is it gets added to the Magento codebase... it's an add-on, it cannot really run without Magento... so it's not a normal dependency that you would manage through composer

**Pull request closed without merging**
